# Standard Library and Gems
require 'set'
require 'stringio'
require 'irb/ruby-lex'
require 'active_support/core_ext/hash'
require 'active_support/core_ext/string/filters'
# Local Files (order matters)
require_relative 'version'
require_relative 'errors'
require_relative 'tokens'
require_relative 'precedence'
require_relative 'operator'
require_relative 'identity'
require_relative 'assignment'
require_relative 'variable'
require_relative 'parser'
require_relative 'ast'
